### ISSUE TITLE
Visual Studio Bridge to Kubernetes "Failed to load current kubeconfig. Please confirm that your kubeconfig is valid."

### ISSUE THREAD

**Issue by mmhealey1** [microsoft/mindaro#111]
![image](https://user-images.githubusercontent.com/52454660/106624929-1353d080-656e-11eb-97c1-9919f959f8df.png)

Visual Studio cannot load my current kubeconfig file running on my machine. I have minikube running on windows 10 via docker desktop using WSL. I have downloaded the extension for VS Code and it recognizes the kubeconfig file just fine:
![image](https://user-images.githubusercontent.com/52454660/106625478-96752680-656e-11eb-95fb-556564b5d895.png)

Here is my kubeconfig for reference:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\Matthew.Healey\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Tue, 02 Feb 2021 13:45:29 GMT
        provider: minikube.sigs.k8s.io
        version: v1.17.0
      name: cluster_info
    server: https://127.0.0.1:49163
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 02 Feb 2021 13:45:29 GMT
        provider: minikube.sigs.k8s.io
        version: v1.17.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\Matthew.Healey\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\Matthew.Healey\.minikube\profiles\minikube\client.key
```

**Comment by amsoedal** [comment]
@mmhealey1 thanks for reporting this issue! Could you please attach the logs from %temp%/Bridge to Kubernetes (or send them to BridgeToKubernetes@microsoft.com)? Thanks in advance!

**Comment by mmhealey1** [comment]
I've just added most recent log file :)

**Comment by mmhealey1** [comment]
I just removed the extensions and it worked. E.g. here is my working kubeconfig:

```yaml
apiVersion: v1
clusters:
  - cluster:
      certificate-authority: C:\Users\Matthew.Healey\.minikube\ca.crt
      server: https://127.0.0.1:49163
    name: minikube
contexts:
  - context:
      cluster: minikube
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: C:\Users\Matthew.Healey\.minikube\profiles\minikube\client.crt
      client-key: C:\Users\Matthew.Healey\.minikube\profiles\minikube\client.key
```
