### ISSUE TITLE
Cannot add the namespace to a service in KubernetesLocalProcessConfig.yaml

### ISSUE THREAD

**Issue by corey-aloia** [microsoft/mindaro#168]
Apply the following yaml:
```
version: 0.1
env:
  - name: my-service
    value: $(services:my-service:9094)
```

Notice that the hostname will be updated to:

`my-service.svc.cluster.local`

now add the namespace:

```
version: 0.1
env:
  - name: my-service
    value: $(services:my-service.mynamespace:9094)
 ```

 And the bridge will not start with 

> Error: An unexpected error occurred: 'Value cannot be null. (Parameter 'source')'

Now try the FQDN
```
version: 0.1
env:
  - name: my-service
    value: $(services:my-service.mynamespace.svc.cluster.local:9094)`
```
the k8 bridge will start, but now the /etc/hosts will have:

`my-service.mynamespace.svc.cluster.local.svc.cluster.local`
