### ISSUE TITLE
Remote cluster services are not available on local development machine

### ISSUE THREAD

**Issue by vBitza** [microsoft/mindaro#188]
I'm not sure what I'm doing wrong but I can't seem to get the remote services to be available for the app I'm trying to debug on the remote cluster.

This is my KubernetesLocalProcessConfig.yaml:
```
version: 0.1
volumeMounts:
  - name: ca.crt
    localPath: /var/run/secrets/kubernetes.io/serviceaccount
env:
  - name: umms
    value: $(services:useradminms-srv.production:80)

```
The app/pod/service (whatever you want to call it) that I'm trying to debug needs to connect to this useradminms-srv which is available and running on the remote cluster. The yaml config seems to be ok, the entry is added in the hosts file:
```
# Added by Bridge To Kubernetes
127.1.1.42 useradminms-srv.production.svc.cluster.local
```

I can even get the variable using process.env.umms from my application but the request doesn't seem to work. This is the error message from the Axios request:
`'connect ETIMEDOUT 127.1.1.42:80'`

I must be missing something out but I just can't figure it out.
