### ISSUE TITLE
Error: Failed to get routing manager deployment status - in the external service usecase

### ISSUE THREAD

**Issue by sunshine69** [microsoft/mindaro#242]
**Describe the bug**
Got this error
```
Failed to establish a connection. Error: Failed to get routing manager deployment status - ran out of time : 'Failed to get routing manager deployment status: 'Service port '80' from ingress 'k8s-qa-api-ingress' does not match any port on the service 'external-website-lo'. 'Please include the following Correlation ID when contacting support: '52f6fa69-25e4-49f6-a459-298d4b424a6f1634528926155:802dcc798265'. '
```
and eventually timeout
 
**To Reproduce**
I followed the steps and use the isolated mode

 
**Expected behavior**
It works
 
**Logs**

 
**Environment Details**
Client used (VS Code/Visual Studio):
<!-- VS Code: `code --list-extensions --show-versions | find "mindaro.mindaro"` 
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.14.14

Operating System: Linux Ubuntu 20.04
Plugin version: v1.0.120210803
 
**Additional context**

From the error it looks like:
- First it tries to duplicate all ingresses in the namespace
- In the ingress it has a path to a service and port (80)
- It looks for the service name and tries to search for port spec
- Normal service works fine, but we have a service of type ExternalName
- Thus it confused and not know what to do in this case

My service yaml is below,

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"external-website-lo","namespace":"k8s-qa"},"spec":{"externalName":"go1moonshotuat.z8.web.core.windows.net","type":"ExternalName"}}
  creationTimestamp: "2021-04-27T01:22:46Z"
  name: external-website-lo
  namespace: k8s-qa
  resourceVersion: "17635129"
  uid: xxxx
spec:
  externalName: go1moonshotuat.z8.web.core.windows.net
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
```
And the ingress route -> backend part is like 
```
      - backend:
          service:
            name: external-website-lo
            port:
              number: 80
        path: /cp
        pathType: Prefix
      - backend:
          service:
            name: external-website-lo
            port:
              number: 80
        path: /assets
        pathType: Prefix
      - backend:
          service:
            name: external-website-lo
            port:
              number: 80
```

The questions are:
- Is service of type ExternalName supported?
- If not supported then is there any plan work to support it?
- is there any work around in the mean time?

Thank you for your help.
