### ISSUE TITLE
Lack of namespacing on service port envvars

### ISSUE THREAD

**Issue by lippylee** [microsoft/mindaro#94]
**Describe the bug**
When launching a debug session with bridge to kubernetes, environment variables are created for each service port. 
For example, for a service named `service-1` there's a corresponding `SERVICE_1_PORT='TCP://127.1.1.29:12345` in the debug envvars.

We use the same naming scheme for configuration, but there's a collision with bridge overwriting our cluster envvars when we run a debug session. It'd be nice if the port envvars are namespaced. For example: `MINDARO_<SERVICE_NAME>_PORT` i.e. `MINDARO_TEST_1_PORT` instead.
 
**To Reproduce**
1. Create a service with name `test-1` and port `12345`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-1
spec:
  selector:
    app: test-1
  ports:
  - port: 12345
    targetPort: 12345
```
2. Create a deployment and service `test_2` that has `TEST_1_PORT` as an environment variable
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-2
  name: test-2
spec:
  selector:
    matchLabels:
      app: test-2
  template:
    metadata:
      labels:
        app: test-2
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: test-2
        env:
        - name: TEST_1_PORT
          value: "12345"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-2
spec:
  selector:
    app: test-2
  ports:
  - port: 8080
    targetPort: 8080
```
3. Start a bridge to kubernetes debug session on the test-2 service:

**launch.json**
```json
{
    "version": "0.2.0",
    "configurations": [
          {
            "name": "test bridge",
            "type": "python",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "program": "test.py",
            "preLaunchTask": "bridge-to-kubernetes.service"
        }
    ]
}
```

**tasks.json**
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "bridge-to-kubernetes.service",
			"type": "bridge-to-kubernetes.service",
			"service": "test-2",
			"ports": [
				8080
			]
		}
	]
}
```

**test.py**
```python
import os
print(os.environ.get('TEST_1_PORT'))
```

**Expected behavior**
`TEST_1_PORT` should be `12345` instead it's `TCP://127.1.1.10:12345`

**Additional context**
k8s exposes service ports as envvars with the name `<SERVICE_NAME>_SERVICE_PORT`. However this requires the services to be up before they can be used.
